# Reccomended value: the same as the framerate of your video/stream.
maximum_framerate: 35
window_resizable: false
max_backups: 500

default_width: 400
default_height: 800

font_file: "default"

# Use "xinput list" to find the ID of your keyboard.
keyboard_id: 10

# Use "xev" to find the IDs. Look for "keycode".
keybindings:
  split: 41 # "F".
  reset: 22 # "Backspace".
  undo: 30 # "U".
  redo: 27 # "R".
