# The message that's displayed in place of the timer whenever it is locked.
timer_locking_message: "Locked"

# Reccomended value: the same as the framerate of your video/stream.
# TODO: move this to splits.
maximum_framerate: 35

window_resizable: false
max_backups: 500

default_width: 400
default_height: 800

# TODO: move this to splits.
font_file: "default"

# TODO: move this to splits.
# Use "xinput list" to find the ID of your keyboard.
keyboard_id: 10

# When a segment is configured to show a given amount of segments per screen, this specifies the
# minimum amount of incomplete segments that must be shown.
# TODO: move this to splits.
min_segments_ahead_to_show: 2

# Use "xev" to find the IDs. Look for "keycode".
# TODO: move this to splits.
global_keybindings:
  key_id_type: "x11"
  split:
    key_id: 41 # "F".
    requires_shift: false
  reset:
    key_id: 22 # "Backspace".
    requires_shift: false
  undo:
    key_id: 30 # "U"
    requires_shift: false
  redo:
    key_id: 27 # "R"
    requires_shift: false
