config_version: 1.0

# Reccomended value: the same as the framerate of your video/stream.
maximum_framerate: 35
window_resizable: false
max_backups: 500

default_width: 400
default_height: 800

font_file: "default"

# Use "xinput list" to find the ID of your keyboard.
keyboard_id: 10

# Use "xev" to find the IDs. Look for "keycode".
global_keybindings:
  key_id_type: "x11"
  split:
    key_id: 41 # "F".
    shift: false
  reset:
    key_id: 22 # "Backspace".
    shift: false
  undo:
    key_id: 30 # "U"
    shift: false
  redo:
    key_id: 27 # "R"
    shift: false
