# Reccomended value: the same as the framerate of your video/stream.
maximum_framerate: 9000

default_width: 400
default_height: 800

font_path: "fonts/PublicPixel-z84yD.ttf"

# Use "xinput list" to find the ID of your keyboard.
keyboard_id: 10

# Use "xev" to find the IDs. Look for "keycode".
keybindings:
  split: 41 # "F".
  reset: 22 # "Backspace".
  undo: 30 # "U".
  redo: 27 # "R".
